# Generated by Django 5.2.10 on 2026-01-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0032_category_exclude_from_menu_category_long_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
