version: '3.8'

services:
  backend:
    build:
      context: ./backend_django
      dockerfile: Dockerfile
    container_name: skintech_backend
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-django-insecure-(%gly^t^q9$$s$$!t2w(^@ya%addg=y5pz_i=ld*z^w05bk%sl5)}
      - DEBUG=${DJANGO_DEBUG:-False}
      # Update ALLOWED_HOSTS if you have a specific domain or IP
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend,host.docker.internal,*
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    # ports:
    #   - "8000:8000"  # Removed to avoid host port conflicts; Nginx proxies it internally

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skintech_frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - media_volume:/app/media
    ports:
      - "80:80"

volumes:
  static_volume:
  media_volume:
