# Generated by Django 5.2.10 on 2026-01-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("inci_name", models.CharField(blank=True, max_length=255, null=True)),
                ("function", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "safety_rating",
                    models.IntegerField(default=5, help_text="1-10, lower is better"),
                ),
                (
                    "comedogenic_rating",
                    models.IntegerField(default=0, help_text="0-5, lower is better"),
                ),
                ("is_allergen", models.BooleanField(default=False)),
                ("is_irritant", models.BooleanField(default=False)),
                ("pregnancy_safe", models.BooleanField(default=True)),
                ("effects", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
