# Generated by Django 5.2.10 on 2026-01-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="description_sq",
            field=models.TextField(blank=True, null=True),
        ),
    ]
